spring.datasource.url: jdbc:mysql://localhost:3306/blog
spring.datasource.username: root
spring.datasource.password: Flatland89268617388)))
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: validate

blog:
  info:
    title: DevPub
    subtitle: Рассказы разработчиков
    phone: +7 903 666-44-55
    email: mail@mail.ru
    copyright: Артем Савичев
    copyrightFrom: 2022

config:
  nameLength: 25
  passwordMinLength: 6
  passwordMaxLength: 12