#Local:
#spring.datasource.url: jdbc:mysql://localhost:3306/blog
#spring.datasource.username: root
#spring.datasource.password: Flatland89268617388)))

#Heroku:
spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog}
server: port=${PORT:8080}

spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: none

blog:
  info:
    title: DevPub
    subtitle: Рассказы разработчиков
    phone: +7 903 666-44-55
    email: artem.savichev@mail.ru
    copyright: Артем Савичев
    copyrightFrom: 2022

config:
  nameLength: 25
  passwordMinLength: 6
  passwordMaxLength: 12
  avatarWidth: 36
  avatarHeight: 36
  imageHeight: 480
  imageWidth: 640
  maxImageSize: 3000000

mail:
  host: smtp.gmail.com
  port: 587
  username: a.savichev13@gmail.com
  password: icxixzyxdxvnadnn